baseURL = 'https://www.thelazyengineer.net/'
languageCode = 'en-us'
title = 'TheLazyEngineer'
since = '2025'
enableGitInfo = true
enableRobotsTXT = true

[taxonomies]
  author = 'authors'
  tag = 'tags'

[permalinks]
  [permalinks.taxonomy]
    tags = "/posts/tags/"
  [permalinks.term]
    tags = "/posts/tags/:slug/"

[pagination]
  pagerSize = 10
  path = 'page'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.highlight]
    noClasses = false
    guessSyntax = false

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
  # [[module.mounts]]
  #   source = "node_modules"
  #   target = "assets/js/lib"
  [module.hugoVersion]
    extended = false
    min = '0.151.0'

# required for TailwindCSS
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
