[build]
  publish = "public/"
  command = 'npm run build:prod'
  [build.environment]
    HUGO_VERSION = "0.152.2"
    HUGO_ENV = "production"
    TZ = "America/Chicago"

[[redirects]]
  from = "/posts/:year/:title/images/:slug"
  to = "/.netlify/images?url=/posts/:year/:title/:slug"
  status = 200
